Example : Banking Account Service with File Store Auth using scopes
ballerina-platform/module-ballerina-auth pull request #1057
Opened 2023-10-16 16:21 UTC by harshalkh

## Purpose
Write Real World Example for Auth:  
Banking Account Service with File Store Basic Auth using scopes 

Fixes 
https://github.com/ballerina-platform/ballerina-standard-library/issues/4819

## Examples

## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [x] Added tests
- [ ] Updated the spec
- [ ] Checked native-image compatibility

2023-10-16 16:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/module-ballerina-auth?pullRequest=1057) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/module-ballerina-auth?pullRequest=1057) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/module-ballerina-auth?pullRequest=1057) it.</sub>

2023-10-17 04:53 UTC, DimuthuMadushan requested changes

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/README.md
> +  will get executed. In this case, it will call the 'Banking Accoint Service' via mTLS and return the response to the 'Client'.
```suggestion
  will get executed. In this case, it will call the 'Banking Account Service' via mTLS and return the response to the 'Client'.
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/README.md
> +```java
```suggestion
```ballerina
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/README.md
> +```shell
```suggestion
```ballerina
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +// WSO2 Inc. licenses this file to you under the Apache License,
```suggestion
// Copyright (c) 2023, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
//
// WSO2 LLC. licenses this file to you under the Apache License,
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +        if(!balAvailable) {
```suggestion
        if !balAvailable {
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +            .toArray();
```suggestion
        AccountWithBalances[] accountBalance = accountBalances
            .filter(acc => acc.customerId == customerId)
            .toArray();
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +            .toArray();
```suggestion
        AccountWithBalances[] accountBalance = accountBalances
            .filter(acc => acc.customerId == customerId)
            .toArray();
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/tests/api_gateway_test.bal
> +//import ballerina/io;
```suggestion
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/tests/api_gateway_test.bal
> +            .toArray();
```suggestion
    AccountWithBalances[] accountBalance = accountBalances
            .filter(acc => acc.customerId == customerId)
            .toArray();
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/tests/api_gateway_test.bal
> +            .toArray();
```suggestion
    AccountWithBalances[] accountBalance = accountBalances
            .filter(acc => acc.customerId == customerId)
            .toArray();
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +            keyFile: "./banking-accounts-service/resources/private.key"
```suggestion
            certFile: "../banking-accounts-service/resources/public.crt",
            keyFile: "../banking-accounts-service/resources/private.key"
```

2023-10-17 04:53 UTC, DimuthuMadushan commented on examples/banking-accounts-service/tests/api_gateway_test.bal
> +        cert: "./banking-accounts-service/resources/public.crt"
```suggestion
        cert: "../banking-accounts-service/resources/public.crt"
```

2023-10-17 04:55 UTC, DimuthuMadushan commented on examples/banking-accounts-service/README.md
> +_Updated_: 2023/10/16
```suggestion
_Authors_: [@harshalkh](https://github.com/harshalkh)  \
_Reviewers_:  @ThisaruGuruge @DimuthuMadushan  \
_Created_: 2023/10/16  \
_Updated_: 2023/10/16
```

2023-10-17 05:29 UTC, ThisaruGuruge commented on examples/banking-accounts-service/README.md
> +will be returning a response from the 'API Gateway' referring to data stored locally in table or records.
As a convention, in these documents, directly ask the reader to do something, instead of trying to go through with them.

Eg.:
- Instead of `We will implement`, use `You will be implementing`.
- Instead of `We can run the following command`, use `Run the following command`. 

When adding a note, use the following notation:

```markdown
> **Note:** <Your Note Goes Here>
```


```suggestion
> **NOTE:** The rest of the components such as Database Management System are not implemented as the main purpose of this article is to showcase the Basic Auth functionalities. But for the completeness of the story, the API Gateway will return a response from the data stored on in-memory tables.
```

2023-10-17 05:29 UTC, ThisaruGuruge commented on examples/banking-accounts-service/README.md
> +Once we are done with the development, we can deploy the service using any of the methods that are listed below.
```suggestion
Once the development is done, you can deploy the service using any of the methods that are listed below.
```

2023-10-17 05:29 UTC, ThisaruGuruge commented on examples/banking-accounts-service/README.md
> +```shell
```suggestion

```shell
```

2023-10-17 05:29 UTC, ThisaruGuruge commented on examples/banking-accounts-service/README.md
> +```shell
```suggestion

```shell
```

2023-10-17 05:29 UTC, ThisaruGuruge commented on examples/banking-accounts-service/README.md
> +```shell
Keep an empty line before a code segment.

```suggestion

```shell
```

2023-10-17 05:29 UTC, ThisaruGuruge commented on examples/banking-accounts-service/api_gateway.bal
> +        accountBalance1[0].balances = [];
We can use a query expression here:

```suggestion
        AccountWithBalances[] accountBalance = from AccountWithBalance account in accountBalance 
                select account 
                where account.customerId == customerId;
        accountBalance[0].balances = [];
```

2023-10-17 05:29 UTC, ThisaruGuruge commented on examples/banking-accounts-service/api_gateway.bal
> +            .toArray();
Shall we try to use [query expressions](https://ballerina.io/learn/by-example/query-expressions/) in these scenarios?

2023-10-17 13:01 UTC, harshalkh commented on examples/banking-accounts-service/api_gateway.bal
> +            .toArray();
Yes suggested changes done.

2023-10-19 08:50 UTC, DimuthuMadushan requested changes

2023-10-19 08:50 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +        return accountBalance1;
Undefined variable?

2023-10-19 08:50 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +                where account.customerId == customerId;
```suggestion
        AccountWithBalances[] accountBalance = from AccountWithBalance account in accountBalances 
                where account.customerId == customerId
                select account;
```

2023-10-19 08:50 UTC, DimuthuMadushan commented on examples/banking-accounts-service/api_gateway.bal
> +                where account.customerId == customerId;
This expression is also wrong. There are few other compilation errors in your code. Please run you code/tests before commit the changes and make sure that they working as expected.

2023-10-19 10:13 UTC, harshalkh commented on examples/banking-accounts-service/api_gateway.bal
> +                where account.customerId == customerId;
Let me check. Earlier it was working looks like the code fixes after review resulted in some issues. Will fix it.

2023-10-19 10:52 UTC, DimuthuMadushan approved these changes
LGTM

2023-10-20 03:47 UTC, ThisaruGuruge commented on examples/banking-accounts-service/README.md
> +routes the requests to 'Banking Service', which is responsible for processing the requests for the customer.
In markdown files, don't use line breaks if the sentence is part of a paragraph. Keep the paragraph in a single line. (This is because some markdown renderers add the new line character, while some don't, which will cause the markdown file to be shown incorrectly. Please check all the places.

2023-10-20 03:51 UTC, ThisaruGuruge commented on examples/banking-accounts-service/api_gateway.bal
> +    {id: "vgskspwldkdddn", accountNumber: "1234 1234 2345", customerId: "david", customerName: "David David", productType: "Savings Account", status: "Active", balances: [ { name: "Available", amount
These lines exceed the 120-character limit. We can format it like this:

```suggestion
    {
        id: "vgshdkrokjhbbb",
        accountNumber: "1234 1234 1234",
        customerId: "alive", 
        customerName: "Alice Alice", 
        productType: "Savings Account", 
        status: "Active", 
        balances: [ 
            { name: "Available", amount: "1000", currency: "INR" }, 
            { name: "Ledger", amount: "1000", currency: "INR" }, 
            { name: "Uncleared", amount: "0", currency: "INR" }
        ]
    },
    {
        id: "vgksurbkfldppd",
        accountNumber: "1234 1234 6789",
        customerId: "bob",
        customerName: "Bob Bob",
        productType: "Current Account",
        status: "Active",
        balances: [
            { name: "Available", amount: "10000", currency: "INR" },
            { name: "Ledger", amount: "1000", currency: "INR" }, 
            { name: "Uncleared", amount: "0", currency: "INR" }
        ]
    },
    {
        id: "vgskspwldkdddn",
        accountNumber: "1234 1234 2345",
        customerId: "David",
        customerName: "David David",
        productType: "Savings Account",
        status: "Active",
        balances: [
            { name: "Available", amount: "8000", currency: "INR" },
            { name: "Ledger", amount: "1000", currency: "INR" },
            { name: "Uncleared", amount: "0", currency: "INR" }
        ]
    }
```

2023-10-20 04:06 UTC, DimuthuMadushan requested changes

2023-10-20 04:06 UTC, DimuthuMadushan commented on examples/banking-accounts-service/README.md
> +[Observing Ballerina Code](https://ballerina.io/learn/user-guide/observability/observing-ballerina-code/) guide provides
```suggestion
[Observing Ballerina Code](https://ballerina.io/learn/observe-ballerina-programs/#provide-observability-in-ballerina) guide provides
```

2023-10-20 04:06 UTC, DimuthuMadushan commented on examples/banking-accounts-service/README.md
> +Refer to [Code to Cloud](https://ballerina.io/learn/user-guide/deployment/code-to-cloud/) guide for more information.
```suggestion
Refer to [Code to Cloud](https://ballerina.io/learn/code-to-cloud-deployment/) guide for more information.
```

2023-10-20 04:06 UTC, DimuthuMadushan commented on examples/banking-accounts-service/README.md
> +navigate to [`examples/banking-account-service/api_gateway`](./api_gateway), and execute the following command for
```suggestion
navigate to [`examples/banking-account-service/api_gateway`](../banking-accounts-service/), and execute the following command for
```

2023-10-20 05:24 UTC, harshalkh commented on examples/banking-accounts-service/README.md
> +routes the requests to 'Banking Service', which is responsible for processing the requests for the customer.
Changes done.

2023-10-20 05:27 UTC, ThisaruGuruge submitted a review, later dismissed
LGTM

2023-10-20 06:20 UTC, DimuthuMadushan approved these changes

2023-10-20 06:30 UTC, merged